apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
      - name: auth-svc
        image: your-repo/auth-svc:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
